const chatbotSuggestions = [
  { id: "intro", label: "Who are you?", prompt: "Who are you?" },
  { id: "phone", label: "What is your phone number?", prompt: "What is your phone number?" },
  { id: "email", label: "What is your email?", prompt: "What is your email?" },
  { id: "social", label: "Where can I connect with you online?", prompt: "Where can I connect with you online?" },
  { id: "linkedin", label: "Do you have a LinkedIn profile?", prompt: "Do you have a LinkedIn profile?" },
  { id: "github", label: "Can I see your GitHub?", prompt: "Can I see your GitHub?" },
  { id: "portfolio", label: "Do you have a portfolio website?", prompt: "Do you have a portfolio website?" },
  { id: "whatsapp", label: "Are you available on WhatsApp?", prompt: "Are you available on WhatsApp?" },
  { id: "learning", label: "What are you currently learning?", prompt: "What are you currently learning?" },
  { id: "skills", label: "What skills do you have?", prompt: "What skills do you have?" },
  { id: "frontend", label: "What are your frontend skills?", prompt: "What are your frontend skills?" },
  { id: "backend", label: "What are your backend skills?", prompt: "What are your backend skills?" },
  { id: "experience", label: "Tell me about your experience", prompt: "Tell me about your experience" },
  { id: "codesfix", label: "What did you do at CodesFix?", prompt: "What did you do at CodesFix?" },
  { id: "bytelogist", label: "What did you do at ByteLogist?", prompt: "What did you do at ByteLogist?" },
  { id: "freelance", label: "Tell me about your freelance work", prompt: "Tell me about your freelance work" },
  { id: "education", label: "What is your education background?", prompt: "What is your education background?" },
  { id: "projects", label: "What projects have you built?", prompt: "What projects have you built?" },
  { id: "ecom", label: "Tell me about your ecommerce project", prompt: "Tell me about your ecommerce project" },
  { id: "study-group", label: "Tell me about Study Group Finder", prompt: "Tell me about Study Group Finder" },
  { id: "task-ai", label: "Tell me about Task Manager AI", prompt: "Tell me about Task Manager AI" },
  { id: "certifications", label: "Do you have any certifications?", prompt: "Do you have any certifications?" },
  { id: "deployment", label: "How do you handle deployments?", prompt: "How do you handle deployments?" },
  { id: "languages", label: "Which programming languages do you know?", prompt: "Which programming languages do you know?" },
  { id: "version-control", label: "How experienced are you with Git?", prompt: "How experienced are you with Git?" },
  { id: "achievements", label: "What achievements or awards do you have?", prompt: "What achievements or awards do you have?" },
  { id: "performance", label: "How do you optimize performance?", prompt: "How do you optimize performance?" },
  { id: "ai", label: "How have you used AI in projects?", prompt: "How have you used AI in projects?" },
  { id: "availability", label: "Are you available for new projects?", prompt: "Are you available for new projects?" },
  { id: "location", label: "Where are you located?", prompt: "Where are you located?" },
  { id: "goals", label: "What are your career goals?", prompt: "What are your career goals?" },
  { id: "greeting", label: "Hello!", prompt: "Hello" }
];

export default chatbotSuggestions;
